version: 2
updates:
  - package-ecosystem: npm
    directory: "/assets"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
