name: Cypress Automation Production Testing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # run at 5 AM UTC
  push:
    branches:
      - 'main'
    paths:
      - '**.csv'
jobs:
  cypress-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Integration tests / Cypress
        uses: cypress-io/github-action@v4
        with:
          env: youth_pass_url=https://mbta.prod.simpligov.com/prod/portal/ShowWorkFlow/AnonymousEmbed/e5e2dba6-5424-48d6-80d9-16a27e0fdd84,senior_url=https://mbta.prod.simpligov.com/prod/portal/ShowWorkFlow/AnonymousEmbed/fc6ff5b0-f3bd-436d-8201-b6a4b98bc7fa
