name: Cypress Automation Production Testing
on: push
  # schedule:
  #   - cron: '0 5 * * *' # run at 5 AM UTC
jobs:
  cypress-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Integration tests / Cypress
        uses: cypress-io/github-action@v2
        with:
          env: youth_pass_url=https://mbta.prod.simpligov.com/prod/portal/ShowWorkFlow/AnonymousEmbed/e5e2dba6-5424-48d6-80d9-16a27e0fdd84
          spec: cypress/automated-tests/youth-pass/address-section-required-fields.spec
          spec: cypress/automated-tests/youth-pass/file-type-upload.spec.js
