name: Automation
on:
  schedule:
    - cron: '0 4 * * *' # run at 4 AM UTC/12 AM EST

jobs:
  cypress:
    name: Integration tests / Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: cypress-io/github-action@v2
      - run: npm run cypress:ci
